package Tortilla.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Tortilla", "Canvas", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba9974bL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:4b93e23c-85d5-42ff-b8c1-3edc1281dd68(Tortilla.structure)/863668800269686603");
    b.version(2);
    b.aggregate("shapes", 0xbfc5e32aba99750L).target(0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99742L).optional(true).ordered(true).multiple(true).origin("863668800269686608").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Tortilla", "Circle", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99743L);
    b.class_(false, false, false);
    b.super_("Tortilla.structure.Shape", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99742L);
    b.origin("r:4b93e23c-85d5-42ff-b8c1-3edc1281dd68(Tortilla.structure)/863668800269686595");
    b.version(2);
    b.property("x", 0xbfc5e32aba99744L).type(PrimitiveTypeId.INTEGER).origin("863668800269686596").done();
    b.property("y", 0xbfc5e32aba99745L).type(PrimitiveTypeId.INTEGER).origin("863668800269686597").done();
    b.property("radius", 0xbfc5e32aba99746L).type(PrimitiveTypeId.INTEGER).origin("863668800269686598").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Tortilla", "Shape", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99742L);
    b.class_(false, true, false);
    b.origin("r:4b93e23c-85d5-42ff-b8c1-3edc1281dd68(Tortilla.structure)/863668800269686594");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Tortilla", "Square", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99747L);
    b.class_(false, false, false);
    b.super_("Tortilla.structure.Shape", 0x3b690b42594e46b6L, 0xb96ff010313cf097L, 0xbfc5e32aba99742L);
    b.origin("r:4b93e23c-85d5-42ff-b8c1-3edc1281dd68(Tortilla.structure)/863668800269686599");
    b.version(2);
    b.property("upperLeftX", 0xbfc5e32aba99748L).type(PrimitiveTypeId.INTEGER).origin("863668800269686600").done();
    b.property("upperLeftY", 0xbfc5e32aba99749L).type(PrimitiveTypeId.INTEGER).origin("863668800269686601").done();
    b.property("size", 0xbfc5e32aba9974aL).type(PrimitiveTypeId.INTEGER).origin("863668800269686602").done();
    b.alias("square");
    return b.create();
  }
}
