package Taco.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class A extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void printComponent(Graphics graphics) {
      super.printComponent(graphics);
      graphics.setColor(Color.green);
      graphics.drawOval(10, 20, 30, 30);
      graphics.setColor(Color.yellow);
      graphics.drawOval(100, 200, 50, 50);
    }
  };

  public void initialize() {
    this.setTitle("A");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    A canvas = new A();
    canvas.initialize();
  }
}
