application: weixugame 
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: .ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
